name: Validate with hassfest

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
